'use strict';

const DB_NAME = 'pwj-web-db';
const DB_VERSION = 1;
const STORE = 'state';
const STATE_KEY = 'main';
const COLORS = {
  BLUE:'#0a84ff', PINK:'#ff375f', GREEN:'#30d158', YELLOW:'#ffd60a', PURPLE:'#bf5af2', ORANGE:'#ff9f0a',
  RED:'#ff453a', TEAL:'#64d2ff', INDIGO:'#5e5ce6', MINT:'#66d4cf', CYAN:'#5ac8fa', BROWN:'#ac8e68', GRAY:'#8e8e93'
};
const ROUTES = ['ORAL','SUBLINGUAL','BUCCAL','INSUFFLATED','INHALED','SMOKED','VAPORIZED','RECTAL','INTRAMUSCULAR','INTRAVENOUS','SUBCUTANEOUS','TRANSDERMAL','OTHER'];
const STOMACH = ['', 'EMPTY', 'LIGHT', 'MEDIUM', 'FULL'];

let state;
let catalog = [];
let categories = [];
let navStack = [];
let currentTab = 'journal';
let searchText = '';
let filterCategory = 'all';
let selectedExperienceId = null;
let installPrompt = null;

const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const esc = s => String(s ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uuid = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(16).slice(2)}`;
const nowMs = () => Date.now();
const colorFor = name => COLORS[(state.companions?.[name] || 'BLUE').toUpperCase()] || COLORS.BLUE;
const toDate = x => new Date(typeof x === 'number' ? x : (Date.parse(x) || Date.now()));
const fmtDate = x => toDate(x).toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).replace('.','');
const fmtTime = x => toDate(x).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});
const titleForDate = x => toDate(x).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
const clamp = (x,a,b) => Math.max(a,Math.min(b,x));

function openDB(){
  return new Promise((resolve,reject)=>{
    const req=indexedDB.open(DB_NAME,DB_VERSION);
    req.onupgradeneeded=()=>{ const db=req.result; if(!db.objectStoreNames.contains(STORE)) db.createObjectStore(STORE); };
    req.onsuccess=()=>resolve(req.result); req.onerror=()=>reject(req.error);
  });
}
async function readState(){ const db=await openDB(); return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly');const r=tx.objectStore(STORE).get(STATE_KEY);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}); }
async function saveState(){ const db=await openDB(); return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(state,STATE_KEY);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)}); }

function seedCustomSubstances(){
  return [
    {id:uuid(),name:'Vortioxetine',units:'mg',unitPlural:'mg',description:'Multimodal serotonergic antidepressant. SERT inhibitor; 5-HT3, 5-HT7 and 5-HT1D antagonist; 5-HT1B partial agonist; 5-HT1A agonist. Oral bioavailability ~75%; Tmax 7–11 h; terminal half-life ~66 h. Primarily CYP2D6 metabolism. Dose/duration bins are custom visualization proxies, not validated PsychonautWiki recreational categories.',color:'PURPLE',subcomponents:[],tolerance:{halfToleranceDays:null,zeroToleranceDays:null},roas:[{name:'oral',dose:{threshold:5,commonMin:10,strongMin:20,heavyMin:null,units:'mg'},duration:{onset:{min:1,max:2,units:'hours'},comeup:{min:5,max:9,units:'hours'},peak:{min:12,max:14,units:'hours'},offset:{min:9,max:12,units:'days'}}}]},
    {id:uuid(),name:'Pramipexole',units:'mg',unitPlural:'mg',description:'D2-like dopamine receptor agonist with preferential D3 affinity. Immediate-release oral formulation. Bioavailability >90%; Tmax ~2 h; terminal half-life ~8–12 h; minimal CYP metabolism; predominantly eliminated unchanged in urine. Dose bins are custom visualization categories rather than validated psychoactive-dose classes.',color:'TEAL',subcomponents:[],tolerance:{halfToleranceDays:null,zeroToleranceDays:null},roas:[{name:'oral',dose:{threshold:0.125,commonMin:0.25,strongMin:0.75,heavyMin:1.5,units:'mg'},duration:{onset:{min:30,max:60,units:'minutes'},comeup:{min:30,max:90,units:'minutes'},peak:{min:2,max:4,units:'hours'},offset:{min:6,max:10,units:'hours'}}}]}
  ];
}
function defaultState(){ return {experiences:[],companions:{Vortioxetine:'PURPLE',Pramipexole:'TEAL'},customSubstances:seedCustomSubstances(),customUnits:[],settings:{theme:'system'},createdAt:nowMs()}; }

async function loadCatalog(){
  for(const url of ['./data/substances.json','../PsychonautWiki%20Journal/substances.json']){
    try{ const r=await fetch(url); if(!r.ok) continue; const d=await r.json(); catalog=d.substances||[]; categories=d.categories||[]; return; }catch(e){}
  }
  catalog=[];
  toast('Base PsychonautWiki não carregou; custom substances continuam disponíveis.');
}
function allSubstances(){
  const custom=(state.customSubstances||[]).map(s=>({...s,isCustom:true,commonNames:[s.name],summary:s.description||'',categories:['custom']}));
  const names=new Set(custom.map(s=>s.name.toLowerCase()));
  return [...custom,...catalog.filter(s=>!names.has((s.name||'').toLowerCase()))];
}
function findSubstance(name){ return allSubstances().find(s=>s.name?.toLowerCase()===String(name).toLowerCase()); }
function normalizeRange(r){ if(!r) return null; let f=1; const u=(r.units||'hours').toLowerCase(); if(u.startsWith('min'))f=1/60; else if(u.startsWith('day'))f=24; else if(u.startsWith('week'))f=168; return {min:(Number(r.min)||0)*f,max:(Number(r.max)||Number(r.min)||0)*f}; }
function routeInfo(sub,route){ return (sub?.roas||[]).find(r=>(r.name||'').toUpperCase()===String(route||'ORAL').toUpperCase()) || (sub?.roas||[])[0]; }
function totalDurationHours(sub,route){ const d=routeInfo(sub,route)?.duration||{}; if(d.total){const t=normalizeRange(d.total);return (t.min+t.max)/2;} return ['onset','comeup','peak','offset'].reduce((a,k)=>{const r=normalizeRange(d[k]);return a+(r?(r.min+r.max)/2:0)},0); }
function doseStrength(sub,route,dose){ const d=routeInfo(sub,route)?.dose||{}; const common=Number(d.commonMin||0); if(!common||!dose)return 1; return clamp(Number(dose)/common,.25,3); }

function applyTheme(){ const t=state.settings?.theme||'system'; document.documentElement.dataset.theme=t==='system'?'':t; }
function toast(msg){ const el=$('#toast'); el.textContent=msg; el.classList.add('show'); clearTimeout(el._t); el._t=setTimeout(()=>el.classList.remove('show'),2200); }

function topbar(title, opts={}){
  const back=opts.back ? `<button class="navbtn" data-action="back">‹ ${esc(opts.backLabel||'Back')}</button>` : '';
  const right=opts.right||'';
  $('#topbar').innerHTML=`<div class="navrow"><div class="navleft">${back}</div><div class="navtitle">${esc(title)}</div><div class="navright">${right}</div></div>${opts.large?`<div class="large-title">${esc(opts.large)}</div>`:''}`;
}
function tabs(){
  const items=[['journal','▤','Journal'],['search','⌕','Search'],['timeline','⌁','Timeline'],['stats','▥','Stats'],['settings','⚙︎','Settings']];
  $('#tabbar').innerHTML=items.map(([id,ico,label])=>`<button class="tab ${currentTab===id?'active':''}" data-tab="${id}"><span class="ico">${ico}</span><span>${label}</span></button>`).join('');
}
function navigate(view,data){ navStack.push({view,data}); renderView(view,data); }
function back(){ navStack.pop(); const prev=navStack.pop(); if(prev) navigate(prev.view,prev.data); else renderTab(currentTab); }
function renderTab(tab){ currentTab=tab; navStack=[]; tabs(); if(tab==='journal') renderJournal(); if(tab==='search') renderSearch(); if(tab==='timeline') renderTimelineTab(); if(tab==='stats') renderStats(); if(tab==='settings') renderSettings(); }
function renderView(view,data){ tabs(); if(view==='substance')renderSubstance(data); if(view==='experience')renderExperience(data); }

function experienceColors(exp){ const names=[...new Set((exp.ingestions||[]).map(i=>i.substanceName))]; return names.map(colorFor); }
function dotHTML(exp){ const cs=experienceColors(exp); if(!cs.length)return `<span class="dot" style="background:#8e8e93"></span>`; if(cs.length===1)return `<span class="dot" style="background:${cs[0]}"></span>`; return `<span class="dot multi-dot" style="--c1:${cs[0]};--c2:${cs[1]}"></span>`; }
function expRow(exp){ const subs=[...new Set((exp.ingestions||[]).map(i=>i.substanceName))].join(' and '); return `<div class="list-row" data-experience="${exp.id}">${dotHTML(exp)}<div class="row-main"><div class="row-title">${esc(exp.title||titleForDate(exp.sortDate||exp.creationDate))}</div><div class="row-sub">${esc(subs||'No ingestions')}</div></div><div class="row-value">${fmtDate(exp.sortDate||exp.creationDate)}</div><span class="chev">›</span></div>`; }
function renderJournal(){
  topbar('Journal',{large:'Journal'});
  const exps=[...(state.experiences||[])].sort((a,b)=>(b.sortDate||b.creationDate)-(a.sortDate||a.creationDate));
  if(!exps.length){$('#screen').innerHTML=`<div class="empty"><div class="big">◉</div><strong>No experiences yet</strong>Log an ingestion to start your journal.</div><button class="fab" data-action="add-ingestion">+</button>`;return;}
  const current=exps[0] && (Date.now()-(exps[0].sortDate||exps[0].creationDate)<36*3600e3) ? [exps[0]] : [];
  const previous=current.length?exps.slice(1):exps;
  $('#screen').innerHTML=`${current.length?`<div class="section-title">Current</div><div class="card">${current.map(expRow).join('')}</div>`:''}<div class="section-title">Previous</div><div class="card">${previous.map(expRow).join('')||'<div class="empty">No previous experiences.</div>'}</div><button class="fab" data-action="add-ingestion">+</button>`;
}

function renderSearch(){
  topbar('Search',{large:'Substances',right:`<button class="navbtn icon" data-action="new-custom">＋</button>`});
  const filtered=allSubstances().filter(s=>{
    const q=searchText.trim().toLowerCase(); const match=!q || [s.name,...(s.commonNames||[])].some(n=>String(n).toLowerCase().includes(q));
    const cat=filterCategory==='all'||(s.categories||[]).includes(filterCategory)||(filterCategory==='custom'&&s.isCustom); return match&&cat;
  }).slice(0,250);
  const cats=['all','custom','stimulant','depressant','psychedelic','dissociative','opioid','antidepressant'];
  $('#screen').innerHTML=`<div class="searchbox"><input id="substance-search" placeholder="Search substances" value="${esc(searchText)}" autocomplete="off"></div><div class="pills">${cats.map(c=>`<button class="pill ${filterCategory===c?'active':''}" data-filter="${c}">${c==='all'?'All':c}</button>`).join('')}</div><div class="card">${filtered.map(s=>`<div class="list-row" data-substance="${esc(s.name)}"><span class="dot" style="background:${s.isCustom?colorFor(s.name):'#8e8e93'}">${s.isCustom?'✎':''}</span><div class="row-main"><div class="row-title">${esc(s.name)}</div><div class="row-sub">${esc((s.categories||[]).slice(0,3).join(' · '))}</div></div><span class="chev">›</span></div>`).join('')||'<div class="empty">Nothing found.</div>'}</div>`;
  setTimeout(()=>{const i=$('#substance-search'); if(i){i.addEventListener('input',e=>{searchText=e.target.value;renderSearch(); const n=$('#substance-search');n?.focus();n?.setSelectionRange(searchText.length,searchText.length);});}},0);
}

function doseSection(roa){ const d=roa?.dose; if(!d)return ''; const pairs=[['Threshold',d.threshold??d.lightMin],['Common',d.commonMin],['Strong',d.strongMin],['Heavy',d.heavyMin]].filter(x=>x[1]!=null); return `<div class="section-caption">Dose · ${esc(roa.name)}</div><div class="card dose-grid">${pairs.map(([k,v])=>`<div class="label">${k}</div><div>${v} ${esc(d.units||'')}</div>`).join('')}</div>`; }
function durationSection(roa){ const d=roa?.duration;if(!d)return ''; const keys=[['onset','Onset'],['comeup','Come-up'],['peak','Peak'],['offset','Offset'],['total','Total'],['afterglow','After effects']]; return `<div class="section-caption">Duration · ${esc(roa.name)}</div><div class="card">${keys.filter(([k])=>d[k]).map(([k,l])=>`<div class="kv"><span>${l}</span><b>${d[k].min}${d[k].max!=null?`–${d[k].max}`:''} ${esc(d[k].units||'')}</b></div>`).join('')}</div>`; }
function renderSubstance(name){
  const s=findSubstance(name); if(!s){back();return;} topbar(s.name,{back:true,backLabel:'Search',right:s.isCustom?`<button class="navbtn" data-edit-custom="${esc(s.name)}">Edit</button>`:''});
  const roas=s.roas||[]; const interactions=s.interactions||{};
  $('#screen').innerHTML=`<div class="hero-substance"><h1>${esc(s.name)}</h1><div class="aliases">${esc((s.commonNames||[]).filter(x=>x!==s.name).slice(0,7).join(' · '))}</div></div>${s.summary||s.description?`<div class="card summary">${esc(s.summary||s.description)}</div>`:''}<div class="section-caption">Categories</div><div class="chips">${(s.categories||['custom']).map(c=>`<span class="chip">${esc(c)}</span>`).join('')}</div>${roas.map(r=>doseSection(r)+durationSection(r)).join('')}${s.tolerance?`<div class="section-caption">Tolerance</div><div class="card">${s.tolerance.full?`<div class="kv"><span>Full tolerance</span><b>${esc(s.tolerance.full)}</b></div>`:''}${s.tolerance.half?`<div class="kv"><span>Half tolerance</span><b>${esc(s.tolerance.half)}</b></div>`:''}${s.tolerance.halfToleranceDays!=null?`<div class="kv"><span>Half tolerance</span><b>${s.tolerance.halfToleranceDays} days</b></div>`:''}${s.tolerance.zero?`<div class="kv"><span>Zero tolerance</span><b>${esc(s.tolerance.zero)}</b></div>`:''}${s.tolerance.zeroToleranceDays!=null?`<div class="kv"><span>Zero tolerance</span><b>${s.tolerance.zeroToleranceDays} days</b></div>`:''}</div>`:''}${(interactions.dangerous?.length||interactions.unsafe?.length||interactions.uncertain?.length)?`<div class="section-caption">Interactions</div><div class="card">${interactions.dangerous?.length?`<div class="kv"><span class="danger">Dangerous</span><b>${esc(interactions.dangerous.join(', '))}</b></div>`:''}${interactions.unsafe?.length?`<div class="kv"><span class="unsafe">Unsafe</span><b>${esc(interactions.unsafe.join(', '))}</b></div>`:''}${interactions.uncertain?.length?`<div class="kv"><span class="uncertain">Uncertain</span><b>${esc(interactions.uncertain.join(', '))}</b></div>`:''}</div>`:''}<div class="spacer"></div><button class="primary" data-action="add-ingestion" data-prefill="${esc(s.name)}">Log ingestion</button>`;
}

function getExperience(id){ return state.experiences.find(e=>e.id===id); }
function timelineSVG(exp){
  const ings=(exp.ingestions||[]).slice().sort((a,b)=>a.time-b.time); if(!ings.length)return '<div class="empty">No ingestions to draw.</div>';
  const start=Math.min(...ings.map(i=>i.time)); const maxEnd=Math.max(...ings.map(i=>i.time+Math.max(totalDurationHours(findSubstance(i.substanceName),i.administrationRoute),2)*3600e3)); const totalH=Math.max((maxEnd-start)/3600e3,6); const W=Math.max(640,totalH*54); const H=220; const left=38,bottom=165,top=28; let svg=`<svg class="timeline-svg" viewBox="0 0 ${W} ${H}" preserveAspectRatio="xMinYMin meet">`;
  const px=(W-left-16)/totalH; for(let h=0;h<=Math.ceil(totalH);h+=Math.max(1,Math.ceil(totalH/12))){const x=left+h*px;const dt=new Date(start+h*3600e3);svg+=`<line x1="${x}" y1="${top}" x2="${x}" y2="${bottom+8}" stroke="var(--line)" stroke-width="1" opacity=".45"/><text x="${x}" y="${bottom+24}" class="timeline-axis" text-anchor="middle">${dt.getHours().toString().padStart(2,'0')}</text>`;}
  ings.forEach((ing,idx)=>{const sub=findSubstance(ing.substanceName); const roa=routeInfo(sub,ing.administrationRoute)||{};const d=roa.duration||{};const phase=k=>{const r=normalizeRange(d[k]);return r?(r.min+r.max)/2:0}; const onset=phase('onset'),come=phase('comeup'),peak=phase('peak'),off=phase('offset'); const x0=left+(ing.time-start)/3600e3*px; const x1=x0+onset*px,x2=x1+come*px,x3=x2+peak*px,x4=x3+off*px; const strength=doseStrength(sub,ing.administrationRoute,ing.dose); const yTop=bottom-clamp(55*strength,35,120); const c=colorFor(ing.substanceName); if(onset+come+peak+off>0){svg+=`<path d="M${x0},${bottom} L${x1},${bottom} L${x2},${yTop} L${x3},${yTop} L${x4},${bottom}" fill="${c}" fill-opacity=".18" stroke="${c}" stroke-width="3" stroke-linejoin="round"/>`;} else {svg+=`<circle cx="${x0}" cy="${bottom-25-idx%3*10}" r="5" fill="${c}"/>`;}
    svg+=`<circle cx="${x0}" cy="${bottom}" r="5" fill="${c}"/><text x="${x0+6}" y="${bottom-8-(idx%3)*15}" class="timeline-label">${esc(ing.substanceName)} ${ing.dose??''}${esc(ing.units||'')}</text>`; });
  svg+=`<line x1="${left}" y1="${bottom}" x2="${W-12}" y2="${bottom}" stroke="var(--text)" stroke-width="1.2"/></svg>`; return svg;
}
function ingestionList(exp){ return (exp.ingestions||[]).slice().sort((a,b)=>a.time-b.time).map(i=>`<div class="list-row ingestion-row"><span class="dot" style="background:${colorFor(i.substanceName)}"></span><div class="row-main"><div class="row-title">${esc(i.substanceName)}</div><div class="row-sub">${fmtTime(i.time)} · ${esc(i.administrationRoute||'ORAL')} ${i.stomachFullness?`· ${esc(i.stomachFullness)}`:''}</div></div><div><b>${i.dose??'—'} ${esc(i.units||'')}</b><div class="dose-dots">●●○○</div></div></div>`).join(''); }
function renderExperience(id){ const exp=getExperience(id);if(!exp){renderTab('journal');return;} selectedExperienceId=id; topbar(exp.title||titleForDate(exp.sortDate),{back:true,backLabel:'Journal',right:`<button class="navbtn icon" data-favorite="${id}">${exp.isFavorite?'★':'☆'}</button>`}); $('#screen').innerHTML=`<div class="section-title">${fmtDate(exp.sortDate||exp.creationDate)}</div><div class="timeline-card">${timelineSVG(exp)}</div><div class="card" style="margin-top:12px">${ingestionList(exp)}</div><div class="section-title">Notes</div><div class="card">${(exp.timedNotes||[]).map(n=>`<div class="note-card"><div class="note-time">${fmtTime(n.time)}</div>${esc(n.note)}</div>`).join('')||'<button class="linkrow" data-add-note="'+id+'">＋ Add Note</button>'}</div>${exp.text?`<div class="section-title">Experience note</div><div class="card note-card">${esc(exp.text)}</div>`:''}<div class="section-title">Location</div><div class="card"><div class="list-row"><div class="row-main"><div class="row-title">${esc(exp.location?.name||'Add Location')}</div></div><span class="chev">›</span></div></div><button class="primary" style="margin-top:18px" data-action="add-ingestion" data-experience-id="${id}">＋ Add Ingestion</button>`; }
function renderTimelineTab(){ topbar('Timeline',{large:'Timeline'}); const exps=[...state.experiences].sort((a,b)=>(b.sortDate||0)-(a.sortDate||0)); const exp=selectedExperienceId?getExperience(selectedExperienceId):exps[0]; if(!exp){$('#screen').innerHTML='<div class="empty"><div class="big">⌁</div><strong>No timeline yet</strong>Log an ingestion first.</div><button class="fab" data-action="add-ingestion">+</button>';return;} selectedExperienceId=exp.id; $('#screen').innerHTML=`<div class="card"><div class="fieldrow"><label>Experience</label><select id="timeline-exp">${exps.map(e=>`<option value="${e.id}" ${e.id===exp.id?'selected':''}>${esc(e.title)}</option>`).join('')}</select></div></div><div class="timeline-card" style="margin-top:12px">${timelineSVG(exp)}</div><div class="card" style="margin-top:12px">${ingestionList(exp)}</div><button class="fab" data-action="add-ingestion" data-experience-id="${exp.id}">+</button>`; $('#timeline-exp')?.addEventListener('change',e=>{selectedExperienceId=e.target.value;renderTimelineTab();}); }

function renderStats(){ topbar('Stats',{large:'Statistics'}); const exps=state.experiences||[]; const cutoff=Date.now()-365*24*3600e3; const recent=exps.filter(e=>(e.sortDate||e.creationDate)>=cutoff); const months=Array(12).fill(0); recent.forEach(e=>{const d=toDate(e.sortDate||e.creationDate); const delta=(new Date().getFullYear()-d.getFullYear())*12+new Date().getMonth()-d.getMonth(); if(delta>=0&&delta<12) months[11-delta]++;}); const counts={}; exps.flatMap(e=>e.ingestions||[]).forEach(i=>counts[i.substanceName]=(counts[i.substanceName]||0)+1); const top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,8); const maxM=Math.max(1,...months),maxC=Math.max(1,...top.map(x=>x[1])); $('#screen').innerHTML=`<div class="card stats-big"><div class="muted">Total Experiences Last 12 Months</div><div class="metric">${recent.length} Experiences</div><div class="bars">${months.map(v=>`<div class="bar" style="height:${Math.max(4,v/maxM*100)}%"></div>`).join('')}</div></div><div class="card stats-big" style="margin-top:14px"><div class="muted">Most Used Substance</div><div class="metric">${esc(top[0]?.[0]||'—')}</div><div class="hbars">${top.map(([n,v])=>`<div class="hbar"><span>${esc(n)}</span><div class="hbar-track"><div class="hbar-fill" style="width:${v/maxC*100}%;background:${colorFor(n)}"></div></div><b>${v}</b></div>`).join('')||'<div class="empty">No data yet.</div>'}</div></div>`; }

function renderSettings(){ topbar('Settings',{large:'Settings'}); const standalone=window.matchMedia('(display-mode: standalone)').matches || navigator.standalone; $('#screen').innerHTML=`${!standalone?`<div class="card install-banner"><strong>Install on iPhone</strong>Open in Safari → Share → <b>Add to Home Screen</b>. After the first load, the app and substance database work offline.</div>`:''}<div class="section-caption">Data</div><div class="card"><button class="linkrow" data-action="export">Export Journal JSON</button><button class="linkrow" data-action="import">Import Journal JSON</button><button class="linkrow" data-action="new-custom">Create Custom Substance</button></div><div class="section-caption">Appearance</div><div class="card"><div class="fieldrow"><label>Theme</label><select id="theme-select"><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></div></div><div class="section-caption">About</div><div class="card"><div class="kv"><span>Catalog</span><b>${catalog.length} substances</b></div><div class="kv"><span>Storage</span><b>Local IndexedDB</b></div><div class="kv"><span>Network</span><b>Not required after cache</b></div><div class="kv"><span>Compatibility</span><b>Journal JSON import/export</b></div></div><div class="section-caption">Danger zone</div><div class="card"><button class="destructive" data-action="reset">Erase local journal data</button></div><input id="import-file" class="hidden" type="file" accept="application/json,.json">`; const ts=$('#theme-select');ts.value=state.settings.theme||'system';ts.onchange=async e=>{state.settings.theme=e.target.value;applyTheme();await saveState();}; }

function modal(html,sheet=false){ $('#modal-root').innerHTML=sheet?`<div class="modal-sheet"><div class="sheet-content">${html}</div></div>`:`<div class="modal">${html}</div>`; }
function closeModal(){ $('#modal-root').innerHTML=''; }
function modalHeader(title,right=''){ return `<div class="modal-head"><div class="navrow"><div class="navleft"><button class="navbtn" data-close-modal>Cancel</button></div><div class="navtitle">${esc(title)}</div><div class="navright">${right}</div></div></div>`; }

function showAddIngestion(prefill='',experienceId=''){
  const exps=[...state.experiences].sort((a,b)=>(b.sortDate||0)-(a.sortDate||0)); const names=allSubstances().map(s=>s.name).sort(); const sub=findSubstance(prefill)||allSubstances()[0]; const route=(sub?.roas?.[0]?.name||'oral').toUpperCase(); const units=routeInfo(sub,route)?.dose?.units||sub?.units||'mg'; const local=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);
  modal(`${modalHeader('New Ingestion',`<button class="navbtn" data-save-ingestion>Done</button>`)}<div style="padding:0 14px 30px"><div class="form-section"><div class="form-title">Substance</div><div class="card"><div class="fieldrow"><label>Name</label><input id="ing-sub" list="sub-list" value="${esc(prefill)}" placeholder="Select substance"><datalist id="sub-list">${names.map(n=>`<option value="${esc(n)}">`).join('')}</datalist></div><div class="fieldrow"><label>Route</label><select id="ing-route">${ROUTES.map(r=>`<option ${r===route?'selected':''}>${r}</option>`).join('')}</select></div><div class="fieldrow"><label>Dose</label><input id="ing-dose" type="number" step="any" inputmode="decimal" placeholder="0"><input id="ing-units" style="max-width:70px" value="${esc(units)}"></div></div></div><div class="form-section"><div class="form-title">Time</div><div class="card"><div class="fieldrow"><label>Date & time</label><input id="ing-time" type="datetime-local" value="${local}"></div><div class="fieldrow"><label>Stomach</label><select id="ing-stomach">${STOMACH.map(v=>`<option value="${v}">${v||'Not set'}</option>`).join('')}</select></div><div class="fieldrow"><label>Estimated dose</label><input id="ing-estimate" type="checkbox" style="flex:0"></div></div></div><div class="form-section"><div class="form-title">Experience</div><div class="card"><div class="fieldrow"><label>Add to</label><select id="ing-exp"><option value="">New experience</option>${exps.map(e=>`<option value="${e.id}" ${experienceId===e.id?'selected':''}>${esc(e.title)}</option>`).join('')}</select></div></div></div><div class="form-section"><div class="form-title">Notes</div><div class="card"><div class="fieldrow"><textarea id="ing-notes" placeholder="Notes"></textarea></div></div></div></div>`);
  $('#ing-sub').addEventListener('change',e=>{const s=findSubstance(e.target.value);const r=(s?.roas?.[0]?.name||'oral').toUpperCase();$('#ing-route').value=ROUTES.includes(r)?r:'ORAL';$('#ing-units').value=routeInfo(s,r)?.dose?.units||s?.units||'mg';});
}
async function saveIngestion(){ const name=$('#ing-sub').value.trim(); if(!name){toast('Choose a substance.');return;} const t=new Date($('#ing-time').value).getTime(); if(!Number.isFinite(t)){toast('Invalid time.');return;} const dose=$('#ing-dose').value===''?null:Number($('#ing-dose').value); const ing={substanceName:name,time:t,endTime:null,creationDate:nowMs(),administrationRoute:$('#ing-route').value,dose,estimatedDoseStandardDeviation:null,isDoseAnEstimate:$('#ing-estimate').checked,units:$('#ing-units').value||'mg',notes:$('#ing-notes').value||'',stomachFullness:$('#ing-stomach').value||null,consumerName:null,customUnitId:null}; let exp=getExperience($('#ing-exp').value); if(!exp){exp={id:uuid(),title:titleForDate(t),text:'',creationDate:nowMs(),sortDate:t,isFavorite:false,ingestions:[],ratings:[],timedNotes:[],location:null};state.experiences.push(exp);} exp.ingestions.push(ing); exp.sortDate=Math.min(...exp.ingestions.map(i=>i.time)); if(!state.companions[name]) state.companions[name]=findSubstance(name)?.color||Object.keys(COLORS)[Object.keys(state.companions).length%Object.keys(COLORS).length]; await saveState(); closeModal(); selectedExperienceId=exp.id; toast('Ingestion saved'); currentTab='journal';tabs();navigate('experience',exp.id); }

function customForm(sub={}){
  const c=sub.color||'PURPLE'; modal(`${modalHeader(sub.name?'Edit':'New Substance',`<button class="navbtn icon" data-save-custom="${esc(sub.name||'')}">✓</button>`)}<div style="padding:0 14px 30px"><div class="form-section"><div class="card"><div class="fieldrow"><label>Name:</label><input id="cs-name" value="${esc(sub.name||'')}" placeholder="Name"></div><div class="fieldrow"><label>Unit singular:</label><input id="cs-unit" value="${esc(sub.units||'mg')}" placeholder="mg"></div><div class="fieldrow"><label>Unit plural:</label><input id="cs-unitp" value="${esc(sub.unitPlural||sub.units||'mg')}" placeholder="mg"></div><div class="fieldrow"><textarea id="cs-notes" placeholder="Notes">${esc(sub.description||'')}</textarea></div><div class="fieldrow"><label>Color</label><select id="cs-color">${Object.keys(COLORS).map(k=>`<option value="${k}" ${k===c?'selected':''}>${k}</option>`).join('')}</select><span id="cs-swatch" class="color-swatch" style="background:${COLORS[c]}"></span></div></div></div><div class="form-title muted">Subcomponents</div><div class="card"><div id="subcomponents">${(sub.subcomponents||[]).map((x,i)=>`<div class="fieldrow"><input class="subcomp" value="${esc(x)}"><button class="navbtn red" data-remove-subcomp="${i}">−</button></div>`).join('')}<button class="linkrow" data-add-subcomponent>Add subcomponent</button></div></div><div class="form-title muted" style="margin-top:28px">Dose & Duration</div><div class="card"><div id="roa-list">${(sub.roas||[]).map((r,i)=>`<button class="linkrow" data-edit-roa="${i}">${esc(r.name||'oral')} · ${esc(r.dose?.units||sub.units||'')} <span style="float:right">›</span></button>`).join('')}</div><button class="linkrow" data-add-roa>Add dose and duration</button></div><div class="form-hint">Dose and duration info draws this custom substance/blend as its own timeline and dosage dots. If none is defined, blends fall back to their subcomponents.</div><div class="form-title muted" style="margin-top:28px">Tolerance</div><div class="card"><div class="fieldrow"><label>Half tolerance:</label><input id="cs-half" type="number" step="any" value="${sub.tolerance?.halfToleranceDays??''}"><span class="muted">Days</span></div><div class="fieldrow"><label>Zero tolerance:</label><input id="cs-zero" type="number" step="any" value="${sub.tolerance?.zeroToleranceDays??''}"><span class="muted">Days</span></div></div><div class="form-hint">Half tolerance is the time to half tolerance from ingestion time. Zero tolerance is the time to zero tolerance from ingestion time.</div>${sub.name?`<div class="form-section"><div class="card"><button class="destructive" data-delete-custom="${esc(sub.name)}">Delete substance</button></div></div>`:''}</div>`); $('#cs-color').onchange=e=>$('#cs-swatch').style.background=COLORS[e.target.value]; $('#modal-root .modal')._editingSub={original:sub.name||'',roas:structuredClone(sub.roas||[]),subcomponents:[...(sub.subcomponents||[])]}; }
function durationRow(label,key,r={}){return `<div class="fieldrow"><label>${label}</label><input id="r-${key}-min" type="number" step="any" placeholder="min" value="${r.min??''}"><span>–</span><input id="r-${key}-max" type="number" step="any" placeholder="max" value="${r.max??''}"><select id="r-${key}-unit"><option ${r.units==='minutes'?'selected':''}>minutes</option><option ${(!r.units||r.units==='hours')?'selected':''}>hours</option><option ${r.units==='days'?'selected':''}>days</option></select></div>`;}
function roaForm(roa={},idx=null){ const d=roa.dose||{},dur=roa.duration||{}; modal(`${modalHeader('Dose & Duration',`<button class="navbtn" data-save-roa="${idx??''}">Done</button>`)}<div style="padding:0 14px 30px"><div class="form-title">Route</div><div class="card"><div class="fieldrow"><label>Route</label><select id="r-name">${ROUTES.map(r=>`<option value="${r.toLowerCase()}" ${(roa.name||'oral').toUpperCase()===r?'selected':''}>${r}</option>`).join('')}</select></div><div class="fieldrow"><label>Units</label><input id="r-units" value="${esc(d.units||'mg')}"></div></div><div class="form-title" style="margin-top:22px">Dose</div><div class="card"><div class="fieldrow"><label>Threshold</label><input id="r-threshold" type="number" step="any" value="${d.threshold??d.lightMin??''}"></div><div class="fieldrow"><label>Common min</label><input id="r-common" type="number" step="any" value="${d.commonMin??''}"></div><div class="fieldrow"><label>Strong min</label><input id="r-strong" type="number" step="any" value="${d.strongMin??''}"></div><div class="fieldrow"><label>Heavy min</label><input id="r-heavy" type="number" step="any" value="${d.heavyMin??''}"></div></div><div class="form-title" style="margin-top:22px">Duration</div><div class="card">${durationRow('Onset','onset',dur.onset)}${durationRow('Come-up','comeup',dur.comeup)}${durationRow('Peak','peak',dur.peak)}${durationRow('Off-set','offset',dur.offset)}${durationRow('Total','total',dur.total)}${durationRow('After effects','afterglow',dur.afterglow)}</div></div>`); $('#modal-root .modal')._roaReturn={roa,idx}; }
function valNum(id){ const v=$(id).value;return v===''?null:Number(v); }
function readRange(k){ const min=valNum(`#r-${k}-min`),max=valNum(`#r-${k}-max`); if(min==null&&max==null)return null; return {min:min??max,max:max??min,units:$(`#r-${k}-unit`).value}; }

function exportJournal(){ const payload={substanceCompanions:Object.entries(state.companions||{}).map(([substanceName,color])=>({substanceName,color})),customSubstances:(state.customSubstances||[]).map(s=>({name:s.name,units:s.units||'mg',description:s.description||'',unitPlural:s.unitPlural,color:s.color,subcomponents:s.subcomponents||[],roas:s.roas||[],tolerance:s.tolerance||{}})),customUnits:state.customUnits||[],experiences:(state.experiences||[]).map(e=>({title:e.title||'',text:e.text||'',creationDate:Number(e.creationDate)||nowMs(),sortDate:e.sortDate==null?null:Number(e.sortDate),isFavorite:!!e.isFavorite,ingestions:(e.ingestions||[]).map(i=>({substanceName:i.substanceName,time:Number(i.time),endTime:i.endTime==null?null:Number(i.endTime),creationDate:i.creationDate==null?null:Number(i.creationDate),administrationRoute:String(i.administrationRoute||'ORAL').toUpperCase(),dose:i.dose,estimatedDoseStandardDeviation:i.estimatedDoseStandardDeviation??null,isDoseAnEstimate:!!i.isDoseAnEstimate,units:i.units||'',notes:i.notes||'',stomachFullness:i.stomachFullness?String(i.stomachFullness).toUpperCase():null,consumerName:i.consumerName??null,customUnitId:i.customUnitId??null})),ratings:e.ratings||[],timedNotes:e.timedNotes||[],location:e.location??null}))}; const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}); const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Journal Web ${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000); }
async function importJournal(file){ try{const obj=JSON.parse(await file.text()); if(!obj||!Array.isArray(obj.experiences))throw new Error('Not a Journal file'); const companions={...state.companions};(obj.substanceCompanions||[]).forEach(c=>companions[c.substanceName]=String(c.color||'BLUE').toUpperCase()); const customs=(obj.customSubstances||[]).map(s=>({id:uuid(),name:s.name,units:s.units||'mg',unitPlural:s.unitPlural||s.units||'mg',description:s.description||'',color:s.color||companions[s.name]||'PURPLE',subcomponents:s.subcomponents||[],roas:s.roas||[],tolerance:s.tolerance||{}})); state={...state,companions,customSubstances:customs.length?customs:state.customSubstances,customUnits:obj.customUnits||[],experiences:obj.experiences.map(e=>({...e,id:uuid(),creationDate:Number(e.creationDate)||nowMs(),sortDate:e.sortDate==null?Math.min(...(e.ingestions||[]).map(i=>Number(i.time))):Number(e.sortDate),ingestions:(e.ingestions||[]).map(i=>({...i,time:Number(i.time),creationDate:i.creationDate==null?null:Number(i.creationDate),endTime:i.endTime==null?null:Number(i.endTime),administrationRoute:String(i.administrationRoute||'ORAL').toUpperCase()})),ratings:e.ratings||[],timedNotes:e.timedNotes||[]}))}; await saveState(); toast(`Imported ${state.experiences.length} experiences`); renderSettings(); }catch(e){console.error(e);toast('Could not import this JSON.');} }

async function handleClick(e){
  const t=e.target.closest('[data-tab],[data-action],[data-experience],[data-substance],[data-edit-custom],[data-close-modal],[data-save-ingestion],[data-favorite],[data-add-note],[data-save-custom],[data-add-subcomponent],[data-remove-subcomp],[data-add-roa],[data-edit-roa],[data-save-roa],[data-delete-custom],[data-filter]'); if(!t)return;
  if(t.dataset.tab){renderTab(t.dataset.tab);return;} if(t.dataset.action==='back'){back();return;} if(t.dataset.experience){navigate('experience',t.dataset.experience);return;} if(t.dataset.substance){navigate('substance',t.dataset.substance);return;} if(t.dataset.filter){filterCategory=t.dataset.filter;renderSearch();return;}
  if(t.hasAttribute('data-close-modal')){closeModal();return;} if(t.dataset.action==='add-ingestion'){showAddIngestion(t.dataset.prefill||'',t.dataset.experienceId||'');return;} if(t.hasAttribute('data-save-ingestion')){await saveIngestion();return;}
  if(t.dataset.action==='new-custom'){customForm({});return;} if(t.dataset.editCustom){customForm(findSubstance(t.dataset.editCustom));return;}
  if(t.dataset.favorite){const x=getExperience(t.dataset.favorite);x.isFavorite=!x.isFavorite;await saveState();renderExperience(x.id);return;}
  if(t.dataset.addNote){const note=prompt('Note');if(note){const x=getExperience(t.dataset.addNote);x.timedNotes=x.timedNotes||[];x.timedNotes.push({creationDate:nowMs(),time:nowMs(),note,color:'BLUE',isPartOfTimeline:true});await saveState();renderExperience(x.id);}return;}
  if(t.dataset.addSubcomponent!==undefined){const m=$('#modal-root .modal');const existing=$$('.subcomp').map(x=>x.value);existing.push('');const name=$('#cs-name').value,unit=$('#cs-unit').value,unitp=$('#cs-unitp').value,notes=$('#cs-notes').value,color=$('#cs-color').value,half=$('#cs-half').value,zero=$('#cs-zero').value; const temp={name,units:unit,unitPlural:unitp,description:notes,color,subcomponents:existing,roas:m._editingSub.roas,tolerance:{halfToleranceDays:half===''?null:Number(half),zeroToleranceDays:zero===''?null:Number(zero)}};customForm(temp);return;}
  if(t.dataset.removeSubcomp!==undefined){const m=$('#modal-root .modal');const existing=$$('.subcomp').map(x=>x.value);existing.splice(Number(t.dataset.removeSubcomp),1);const temp={name:$('#cs-name').value,units:$('#cs-unit').value,unitPlural:$('#cs-unitp').value,description:$('#cs-notes').value,color:$('#cs-color').value,subcomponents:existing,roas:m._editingSub.roas,tolerance:{halfToleranceDays:$('#cs-half').value===''?null:Number($('#cs-half').value),zeroToleranceDays:$('#cs-zero').value===''?null:Number($('#cs-zero').value)}};customForm(temp);return;}
  if(t.dataset.addRoa!==undefined){const m=$('#modal-root .modal'); window.__customDraft={original:m._editingSub.original,name:$('#cs-name').value,units:$('#cs-unit').value,unitPlural:$('#cs-unitp').value,description:$('#cs-notes').value,color:$('#cs-color').value,subcomponents:[...m._editingSub.subcomponents],roas:[...m._editingSub.roas],tolerance:{halfToleranceDays:$('#cs-half').value===''?null:Number($('#cs-half').value),zeroToleranceDays:$('#cs-zero').value===''?null:Number($('#cs-zero').value)}};roaForm({dose:{units:$('#cs-unit').value||'mg'},duration:{}},null);return;}
  if(t.dataset.editRoa!==undefined){const m=$('#modal-root .modal');const i=Number(t.dataset.editRoa);window.__customDraft={original:m._editingSub.original,name:$('#cs-name').value,units:$('#cs-unit').value,unitPlural:$('#cs-unitp').value,description:$('#cs-notes').value,color:$('#cs-color').value,subcomponents:[...m._editingSub.subcomponents],roas:[...m._editingSub.roas],tolerance:{halfToleranceDays:$('#cs-half').value===''?null:Number($('#cs-half').value),zeroToleranceDays:$('#cs-zero').value===''?null:Number($('#cs-zero').value)}};roaForm(m._editingSub.roas[i],i);return;}
  if(t.dataset.saveRoa!==undefined){const idx=t.dataset.saveRoa===''?null:Number(t.dataset.saveRoa);const dose={units:$('#r-units').value,threshold:valNum('#r-threshold'),commonMin:valNum('#r-common'),strongMin:valNum('#r-strong'),heavyMin:valNum('#r-heavy')};const duration={};for(const k of ['onset','comeup','peak','offset','total','afterglow']){const r=readRange(k);if(r)duration[k]=r;}const r={name:$('#r-name').value,dose,duration};const draft=window.__customDraft;if(idx==null)draft.roas.push(r);else draft.roas[idx]=r;customForm(draft);window.__customDraft=null;return;}
  if(t.dataset.saveCustom!==undefined){const m=$('#modal-root .modal');const name=$('#cs-name').value.trim();if(!name){toast('Name is required');return;}const obj={id:findSubstance(m._editingSub.original)?.id||uuid(),name,units:$('#cs-unit').value||'mg',unitPlural:$('#cs-unitp').value||$('#cs-unit').value||'mg',description:$('#cs-notes').value||'',color:$('#cs-color').value,subcomponents:m._editingSub.subcomponents.map((x,i)=>$$('.subcomp')[i]?.value??x).filter(Boolean),roas:m._editingSub.roas,tolerance:{halfToleranceDays:$('#cs-half').value===''?null:Number($('#cs-half').value),zeroToleranceDays:$('#cs-zero').value===''?null:Number($('#cs-zero').value)}};const idx=state.customSubstances.findIndex(s=>s.name===m._editingSub.original);if(idx>=0)state.customSubstances[idx]=obj;else state.customSubstances.push(obj);if(m._editingSub.original&&m._editingSub.original!==name){delete state.companions[m._editingSub.original];}state.companions[name]=obj.color;await saveState();closeModal();toast('Substance saved');currentTab='search';renderSearch();navigate('substance',name);return;}
  if(t.dataset.deleteCustom){if(confirm(`Delete ${t.dataset.deleteCustom}?`)){state.customSubstances=state.customSubstances.filter(s=>s.name!==t.dataset.deleteCustom);await saveState();closeModal();renderTab('search');}return;}
  if(t.dataset.action==='export'){exportJournal();return;} if(t.dataset.action==='import'){$('#import-file').click();return;} if(t.dataset.action==='reset'){if(confirm('Erase experiences and local custom data?')){state=defaultState();await saveState();applyTheme();renderSettings();toast('Local data erased');}return;}
}

document.addEventListener('click',handleClick);
document.addEventListener('change',e=>{if(e.target.id==='import-file'&&e.target.files?.[0])importJournal(e.target.files[0]);});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});
window.addEventListener('hashchange',()=>{const t=location.hash.replace('#','');if(['journal','search','timeline','stats','settings'].includes(t))renderTab(t);});

async function init(){ state=await readState()||defaultState(); state.experiences=(state.experiences||[]).map(e=>({...e,id:e.id||uuid()})); state.customSubstances=state.customSubstances||[];state.companions=state.companions||{};state.settings=state.settings||{theme:'system'};applyTheme();await loadCatalog(); tabs(); const h=location.hash.replace('#','');renderTab(['journal','search','timeline','stats','settings'].includes(h)?h:'journal'); if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('./sw.js')}catch(e){console.warn(e)}} }
init();
